/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ItemsRouteImport } from './routes/items'
import { Route as HeroesRouteImport } from './routes/heroes'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HeroesHeroSlugRouteImport } from './routes/heroes_.$heroSlug'

const ItemsRoute = ItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => rootRouteImport,
} as any)
const HeroesRoute = HeroesRouteImport.update({
  id: '/heroes',
  path: '/heroes',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HeroesHeroSlugRoute = HeroesHeroSlugRouteImport.update({
  id: '/heroes_/$heroSlug',
  path: '/heroes/$heroSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/heroes': typeof HeroesRoute
  '/items': typeof ItemsRoute
  '/heroes/$heroSlug': typeof HeroesHeroSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/heroes': typeof HeroesRoute
  '/items': typeof ItemsRoute
  '/heroes/$heroSlug': typeof HeroesHeroSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/heroes': typeof HeroesRoute
  '/items': typeof ItemsRoute
  '/heroes_/$heroSlug': typeof HeroesHeroSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/compare' | '/heroes' | '/items' | '/heroes/$heroSlug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/compare' | '/heroes' | '/items' | '/heroes/$heroSlug'
  id:
    | '__root__'
    | '/'
    | '/compare'
    | '/heroes'
    | '/items'
    | '/heroes_/$heroSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompareRoute: typeof CompareRoute
  HeroesRoute: typeof HeroesRoute
  ItemsRoute: typeof ItemsRoute
  HeroesHeroSlugRoute: typeof HeroesHeroSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/items': {
      id: '/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heroes': {
      id: '/heroes'
      path: '/heroes'
      fullPath: '/heroes'
      preLoaderRoute: typeof HeroesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heroes_/$heroSlug': {
      id: '/heroes_/$heroSlug'
      path: '/heroes/$heroSlug'
      fullPath: '/heroes/$heroSlug'
      preLoaderRoute: typeof HeroesHeroSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareRoute: CompareRoute,
  HeroesRoute: HeroesRoute,
  ItemsRoute: ItemsRoute,
  HeroesHeroSlugRoute: HeroesHeroSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
