/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout.index'
import { Route as LayoutCompareRouteImport } from './routes/_layout.compare'
import { Route as LayoutHeroesRouteImport } from './routes/_layout.heroes'
import { Route as LayoutItemsRouteImport } from './routes/_layout.items'
import { Route as LayoutHeroesHeroSlugRouteImport } from './routes/_layout.heroes_.$heroSlug'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCompareRoute = LayoutCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutHeroesRoute = LayoutHeroesRouteImport.update({
  id: '/heroes',
  path: '/heroes',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutHeroesHeroSlugRoute = LayoutHeroesHeroSlugRouteImport.update({
  id: '/heroes_/$heroSlug',
  path: '/heroes/$heroSlug',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/compare': typeof LayoutCompareRoute
  '/heroes': typeof LayoutHeroesRoute
  '/items': typeof LayoutItemsRoute
  '/heroes/$heroSlug': typeof LayoutHeroesHeroSlugRoute
}
export interface FileRoutesByTo {
  '/compare': typeof LayoutCompareRoute
  '/heroes': typeof LayoutHeroesRoute
  '/items': typeof LayoutItemsRoute
  '/': typeof LayoutIndexRoute
  '/heroes/$heroSlug': typeof LayoutHeroesHeroSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/compare': typeof LayoutCompareRoute
  '/_layout/heroes': typeof LayoutHeroesRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/heroes_/$heroSlug': typeof LayoutHeroesHeroSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/compare' | '/heroes' | '/items' | '/heroes/$heroSlug'
  fileRoutesByTo: FileRoutesByTo
  to: '/compare' | '/heroes' | '/items' | '/' | '/heroes/$heroSlug'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/compare'
    | '/_layout/heroes'
    | '/_layout/items'
    | '/_layout/'
    | '/_layout/heroes_/$heroSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/compare': {
      id: '/_layout/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof LayoutCompareRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/heroes': {
      id: '/_layout/heroes'
      path: '/heroes'
      fullPath: '/heroes'
      preLoaderRoute: typeof LayoutHeroesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/heroes_/$heroSlug': {
      id: '/_layout/heroes_/$heroSlug'
      path: '/heroes/$heroSlug'
      fullPath: '/heroes/$heroSlug'
      preLoaderRoute: typeof LayoutHeroesHeroSlugRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutCompareRoute: typeof LayoutCompareRoute
  LayoutHeroesRoute: typeof LayoutHeroesRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutHeroesHeroSlugRoute: typeof LayoutHeroesHeroSlugRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutCompareRoute: LayoutCompareRoute,
  LayoutHeroesRoute: LayoutHeroesRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutHeroesHeroSlugRoute: LayoutHeroesHeroSlugRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
